# Generated by Django 2.1.2 on 2018-10-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=26, unique=True)),
                ('user_first', models.CharField(max_length=26)),
                ('user_last', models.CharField(max_length=20)),
            ],
        ),
    ]
