# Generated by Django 2.1.2 on 2018-10-22 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_first',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_last',
        ),
    ]
